//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class AssetUser
    {
        public AssetUser()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public string AspNetUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }


        //Will the ORM know this isn't a database Column? 
        [Display(Name = "Owner")]
        public String fullName
        {
            get { return this.getFullName(); }
        }
        public String getFullName()
        {
            string fullName = String.Concat(this.LastName, " ", this.FirstName);
            return fullName;
        }
    }
}
