//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Asset
    {
        public int Id { get; set; }
        public Nullable<int> AssetModelId { get; set; }
        
       
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date)]
        [Display(Name="Purchase Date")]
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        
        [Display(Name="Serial Number")]
        public string SerialNumber { get; set; }
        
        [RegularExpression(@"^\D+\d+$", ErrorMessage= "Plese enter a valid room number")]
        [Display(Name="Room Number")]
        public string RoomNum { get; set; }
        
        
      
        public string AssetOwner { get; set; }
    
        public virtual AssetModel AssetModel { get; set; }
        public virtual AssetUser AssetUser { get; set; }

    }
}
