//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.AssetUsers = new HashSet<AssetUser>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AssetModelId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string SerialNumber { get; set; }
        public string RoomNum { get; set; }
    
        public virtual AssetModel AssetModel { get; set; }
        public virtual ICollection<AssetUser> AssetUsers { get; set; }
    }
}
