//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace InventoryManagement
{
    using System;
    using System.Collections.Generic;
using System.Web.Mvc;
    
    public partial class AssetModel
    {
        public int Id { get; set; }

        public AssetModel()
        {
            this.Assets = new HashSet<Asset>();
        }

        [Display(Name="Model")]
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual AssetType AssetType { get; set; }
    }
}
